name: Notify super-repo
on:
  push:
    branches: [main]

jobs:
  ping:
    runs-on: [self-hosted, Linux, X64, trusted, docker]
    permissions:
      contents: read
      actions: read
    env:
      SUPER_REPO: mbarleon-org/Area
    steps:
      - name: Dispatch event to super-repo
        run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            https://api.github.com/repos/$SUPER_REPO/dispatches \
            -d "{\"event_type\":\"submodule-updated\",\"client_payload\":{\"repo\":\"${{ github.repository }}\",\"sha\":\"${{ github.sha }}\"}}"
